=== M1niMike/AutoresRegex/autores.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="autores">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="autor">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="nome" type="xs:string" />
                <xs:element name="dataNascimento" type="xs:string" />
                <xs:element name="dataMorte" type="xs:string" />
                <xs:element name="nacionalidade" type="xs:string" />
                <xs:element name="generoLiterario" type="xs:string" />
                <xs:element name="ocupacoes">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element maxOccurs="unbounded" name="ocupacao" type="xs:string" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="conjuge" type="xs:string" />
                <xs:element name="linkFoto" type="xs:string" />
                <xs:element name="premios">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="premio" type="xs:string" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== M1niMike/AutoresRegex/autores.xml
<?xml version="1.0" encoding="utf-8"?>
<autores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="autores.xsd">
     <autor id="15">
          <nome>Nicholas Sparks</nome>
          <dataNascimento>31 de dezembro 1965</dataNascimento>
          <dataMorte>O Autor ainda esta vivo</dataMorte>
          <nacionalidade>norte-americano</nacionalidade>
          <generoLiterario>Sem informacao</generoLiterario>
          <ocupacoes>
               <ocupacao>Escritor</ocupacao>
               <ocupacao>roteirista</ocupacao>
               <ocupacao>produtor</ocupacao>
          </ocupacoes>
          <conjuge>Cathy Sparks (1989-2015)</conjuge>
          <linkFoto>https://upload.wikimedia.org/wikipedia/commons/a/af/Nicholas-Sparks-Autograph-1-4-06.jpg</linkFoto>
          <premios>
               <premio>Nobel</premio>
          </premios>
     </autor>
     <autor id="24">
          <nome>Fernando Pessoa</nome>
          <dataNascimento>13 de junho 1888</dataNascimento>
          <dataMorte>30 de novembro 1935</dataMorte>
          <nacionalidade>Português</nacionalidade>
          <generoLiterario>Sem informacao</generoLiterario>
          <ocupacoes>
               <ocupacao>Poeta</ocupacao>
               <ocupacao>escritor</ocupacao>
               <ocupacao>tradutor</ocupacao>
          </ocupacoes>
          <premios>
               <premio>Prémio Antero de Quental</premio>
          </premios>
          <conjuge>Sem informacao</conjuge>
          <linkFoto>https://upload.wikimedia.org/wikipedia/commons/3/32/Pessoa_chapeu.jpg</linkFoto>
     </autor>
</autores>
