=== M1niMike/AutoresRegex/escritores/escritores.dtd
<!ELEMENT escritores (nome)>
<!ELEMENT nome (dataNascimento,dataMorte,nacionalidade,generoLiterario,ocupacoes,premios,conjuge)>
<!ATTLIST nome id NMTOKEN #REQUIRED>
<!ELEMENT dataNascimento EMPTY>
<!ELEMENT dataMorte EMPTY>
<!ELEMENT nacionalidade EMPTY>
<!ELEMENT generoLiterario EMPTY>
<!ELEMENT ocupacoes EMPTY>
<!ELEMENT premios EMPTY>
<!ELEMENT conjuge EMPTY>

=== M1niMike/AutoresRegex/escritores/escritores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores SYSTEM "escritores.dtd">
<escritores>
    <nome id="1">
        <dataNascimento></dataNascimento>
        <dataMorte></dataMorte>
        <nacionalidade></nacionalidade>
        <generoLiterario></generoLiterario>
        <ocupacoes></ocupacoes>
        <premios></premios>
        <conjuge></conjuge>
    </nome>
</escritores>
