=== M1niMike/AutoresRegex/obras/obras.dtd
<!ELEMENT obras (livro)>
<!ELEMENT livro (isbn,titulo,autor,editora,preco,quantidadePaginas,idioma,encadernacao)>
<!ELEMENT isbn EMPTY>
<!ELEMENT titulo EMPTY>
<!ELEMENT autor EMPTY>
<!ELEMENT editora EMPTY>
<!ELEMENT preco EMPTY>
<!ELEMENT quantidadePaginas EMPTY>
<!ELEMENT idioma EMPTY>
<!ELEMENT encadernacao EMPTY>

=== M1niMike/AutoresRegex/obras/obras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE obras SYSTEM "obras.dtd">
<obras>
    <livro>
        <isbn></isbn>
        <titulo></titulo>
        <autor></autor>
        <editora></editora>
        <preco></preco>
        <quantidadePaginas></quantidadePaginas>
        <idioma></idioma>
        <encadernacao></encadernacao>
    </livro>
</obras>
